version: "3.8"

services:
  backend:
    image: ghcr.io/minihackathon2-0/learnify-backend:latest
    container_name: express-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env
    restart: on-failure

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: on-failure

  frontend:
    image: ghcr.io/minihackathon2-0/learnify-frontend:latest
    container_name: nginx-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: on-failure

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
