name: Build

on:
  workflow_call:

jobs:
  build_and_push_fe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the frontend repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: echo "LOWERCASE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: Frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.LOWERCASE_OWNER }}/learnify-frontend:latest

  trigger_deploy_fe:
    name: Trigger deploy
    needs: build_and_push_fe
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: frontend

  build_and_push_be:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the backend repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: echo "LOWERCASE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: Backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.LOWERCASE_OWNER }}/learnify-backend:latest

  trigger_deploy_be:
    name: Trigger deploy
    needs: build_and_push_be
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: backend
